[MailServer]
  ServerAddress = "smtp.exmail.qq.com"
  ServerAddressPort = 465
  NeedLogin = true
  LoginUser = "guohongjun@bbb.com"
  LoginPassword = "*******"
  [MailServer.SendMailUserMail]
    Name = "郭红俊"
    Address = "guohongjun@bbb.com"

[[ConfigArr]]
  FileName = "/Users/ghj1976/project/mygocode/src/github.com/ghj1976/tailMail/test/11.log"
  FileNameUseTemplate = false
  Subject = "异常监控报告，服务器：61.235"
  Remark = ""

  [[ConfigArr.ToMailArr]]
    Name = "ghj1976"
    Address = "ghj1976@aaa.com"

  [[ConfigArr.ToMailArr]]
    Name = "郭红俊"
    Address = "guohongjun@bbb.com"

[[ConfigArr]]
  FileName = "/Users/ghj1976/project/mygocode/src/github.com/ghj1976/tailMail/test/22_{{formatNow \"2006-01-02\"}}.log"
  FileNameUseTemplate = true
  Subject = "测试邮件标题"
  Remark = ""

  [[ConfigArr.ToMailArr]]
    Name = "ghj1976"
    Address = "ghj1976@aaa.com"

[Stat]
  Enable = true
  ServerName = "10.162.222.210"
